# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  ####################### Box Settings #######################
  config.vm.box = "centos/7"

  ####################### Provider Settings #######################
   config.vm.provider "virtualbox" do |vb|
  ####################### machine name #######################
    vb.name = "ServerWorker"
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "512"
     # Customize the amount of cpu on the VM:
     vb.cpus = 1
  end
  ####################### Network Settings #######################
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "public_network"
    config.vm.network "private_network", ip: "192.168.42.111"
  #Kubernetes API Access
    config.vm.network "forwarded_port", guest: 6443, host: 6443
  # Expose NodePort ports
  for p in 30000..30100
    config.vm.network "forwarded_port", guest: p, host: p, protocol: "tcp"
  end

  ####################### Folder Settings #######################
  # config.vm.synced_folder "../data", "/vagrant_data"
  
  ####################### Provision Settings #######################
  # Run some setup script to install K3s on he VM
    config.vm.provision "shell", inline: "curl -sfL https://get.k3s.io | sh -"
    
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
