apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    app.kubernetes.io/name: playground
    app.kubernetes.io/instance: playground-one
    app.kubernetes.io/version: "v1"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
        tier: backend
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1 
        ports:
        - containerPort: 8888