# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  control.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "khimyaS"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.memory = 512
    vb.cpus = 1
  end
  # Install net-tools for all machines  
  config.vm.provision "shell", inline: <<-SHELL
    yum update -y && yum install -y net-tools
  SHELL

  config.vm.define "khimyaS" do |control|
    control.vm.hostname = "khimyaS"
    control.vm.network "private_network", ip: "192.168.42.110"
    control.vm.provision "shell", privileged: true, path: "scripts/installS.sh"
  end
  
  config.vm.define "oouklichSW" do |control|
    control.vm.hostname = "oouklichSW"
    control.vm.network "private_network", ip: "192.168.42.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "oouklichSW"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 512
      v.cpus = 1
    end
    control.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    control.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"
    control.vm.provision "shell", privileged: true, path: "scripts/installSW.sh"
  end

end