Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "ybenbraiS"
    config.vm.network "private_network", ip: "192.168.42.110"
    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", "1"]
        v.customize ["modifyvm", :id, "--name", "ybenbraiS"]
    end
    config.vm.provision "shell", inline: <<-SHELL
        yum -y install net-tools
        export K3S_KUBECONFIG_MODE="644"
        export INSTALL_K3S_EXEC="--flannel-iface eth1"
        curl -sfL https://get.k3s.io | sh -
        /usr/local/bin/kubectl apply -f /vagrant/confs/app1.yaml
        /usr/local/bin/kubectl apply -f /vagrant/confs/app2.yaml
        /usr/local/bin/kubectl apply -f /vagrant/confs/app3.yaml
        /usr/local/bin/kubectl apply -f /vagrant/confs/ingress.yaml
        SHELL
end