# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"

  config.vm.define "oelazzouS"
  config.vm.hostname = "oelazzouS"
  config.vm.network "private_network", ip: "192.168.42.110"
  config.vm.provision "file", source: "config/app-one.yml", destination: "/tmp/app-one.yml"
  config.vm.provision "file", source: "config/app-two.yml", destination: "/tmp/app-two.yml"
  config.vm.provision "file", source: "config/app-three.yml", destination: "/tmp/app-three.yml"
  config.vm.provision "file", source: "config/ingress.yml", destination: "/tmp/ingress.yml"
  config.vm.provision "file", source: "config/svc.yml", destination: "/tmp/svc.yml"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpus", "1"]
    v.customize ["modifyvm", :id, "--memory", "1024"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--name", "oelazzouS"]
  end
  config.vm.provision "shell", privileged: true, path: "scripts/script.sh"
  config.vm.provision "shell", inline: "/usr/local/bin/kubectl apply -f /home/vagrant/", privileged: false
end