MASTER_HOSTNAME = "ybenbraiS"
MASTER_IP = "192.168.42.110"

WORKER_HOSTNAME = "ybenbraiSW"
WORKER_IP = "192.168.42.111"

VB = "virtualbox"
MEMORY = 512
CPU = 1
BOX = "centos/7"

Vagrant.configure("2") do |config|
	config.vm.define MASTER_HOSTNAME do |settings|
		settings.vm.box = BOX
		settings.vm.hostname = MASTER_HOSTNAME
		settings.vm.network "private_network", ip: MASTER_IP
		settings.vm.provider VB do |vb|
			vb.memory = MEMORY
			vb.cpus = CPU
			vb.name = MASTER_HOSTNAME
		end
		settings.vm.provision "shell", inline: <<-SHELL
		yum -y install net-tools
		export K3S_KUBECONFIG_MODE="644"
		export INSTALL_K3S_EXEC="--flannel-iface eth1"
		curl -sfL https://get.k3s.io | sh -
		SHELL
		s.trigger.after :up do |trigger|
			trigger.run = {inline: "bash -c 'vagrant ssh atalebS -c \"sudo /bin/cat /var/lib/rancher/k3s/server/node-token\" > ./token '"}
		end
	end
	
	config.vm.define WORKER_HOSTNAME do |settings|
		settings.vm.box = BOX
		settings.vm.hostname = WORKER_HOSTNAME
		settings.vm.network "private_network", ip: WORKER_IP
		settings.vm.provider VB do |vb|
		  vb.memory = MEMORY
		  vb.cpus = CPU
		  vb.name = WORKER_HOSTNAME
		end
		settings.vm.provision "shell", inline: <<-SHELL
		yum -y install net-tools
		export K3S_KUBECONFIG_MODE="644"
		export INSTALL_K3S_EXEC="--flannel-iface eth1"
		export K3S_URL="https://${MASTER_IP}:6443"
		export K3S_TOKEN_FILE="/vagrant/token"
		curl -sfL https://get.k3s.io | sh -
		SHELL
	end
end