Vagrant.configure("2") do |config|

	config.vm.define "ybenbraiS" do |s|
		s.vm.box = "centos/7"
		s.vm.hostname = "ybenbraiS"
		s.vm.network "private_network", ip: "192.168.42.110"
		s.vm.provider "virtualbox" do |v|
			v.memory = 512
			v.cpus = 1
			v.name = "ybenbraiS"
		end
		s.vm.provision "shell", inline: <<-SHELL
		yum -y install net-tools
		export K3S_KUBECONFIG_MODE="644"
		export INSTALL_K3S_EXEC="--flannel-iface eth1"
		curl -sfL https://get.k3s.io | sh -
		SHELL
		s.trigger.after :up do |trigger|
			trigger.run = {inline: "bash -c 'vagrant ssh ybenbraiS -c \"sudo /bin/cat /var/lib/rancher/k3s/server/node-token\" > ./token '"}
		end
	end
	
	config.vm.define "ybenbraiSW" do |sw|
		sw.vm.box = "centos/7"
		sw.vm.hostname = "ybenbraiSW"
		sw.vm.network :private_network, ip: "192.168.42.111"
		sw.vm.provider :virtualbox do |v|
			v.memory = 512
			v.cpus = 1
			v.name = "ybenbraiSW"
		end
		sw.vm.provision "shell", inline: <<-SHELL 
		yum -y install net-tools
		export INSTALL_K3S_EXEC="--flannel-iface eth1"
		export K3S_KUBECONFIG_MODE="644"
		export K3S_URL="https://192.168.42.110:6443"
		export K3S_TOKEN_FILE="/vagrant/token"
		curl -sfL https://get.k3s.io | sh -
		SHELL
	end
end