# -*- mode: ruby -*-
# vi: set ft=ruby :

#ks3 token
K3S_TOKEN = 'my_super_secret_token'
# master config
MASTER_NAME = 'ybenbraiS'
MASTER_IP = '192.168.42.110'

#agent config
WORKER_NAME = 'ybenbraiSW'
WORKER_IP = '192.168.42.111'

# common config
MEMORY = 1024
CPU = 1
BOX = "centos/8"
BOX_UPDATE = false

# disable firewall so we can have direct ssh access without need to copy our ssh public key to the machine 
# !!! (NOT RECOMMENDED , USE THE SSH KEYS METHOD IN PRODUCTION ENV, THIS IS ONLY FOR SCHOOL PRACTICING PURPOSE ) !!!
$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL


Vagrant.configure("2") do |config|
	config.vm.box = BOX
	config.vm.box_check_update = BOX_UPDATE
  
config.vm.provider "virtualbox" do |v|
	v.memory = MEMORY
	v.cpus = CPU
	end

config.vm.provision "shell",  path: "scripts/bootstrap_centos.sh"

config.vm.define MASTER_NAME , primary: true do |master|
	master.vm.hostname = MASTER_NAME
	master.vm.network :private_network, ip: MASTER_IP
	master.vm.provision "shell",
	env: {"NODE_IP" => MASTER_IP, "WORKER_IP" => WORKER_IP, "WORKER_HOSTNAME" => WORKER_NAME, "TOKEN" => K3S_TOKEN},
	inline:  <<-EOF
	  set -eu
	  echo "$WORKER_IP $WORKER_HOSTNAME" >> /etc/hosts
	  curl -sfL https://get.k3s.io \
		| INSTALL_K3S_EXEC="--cluster-init --node-ip=${NODE_IP} --token=${TOKEN} --no-deploy=traefik --write-kubeconfig-mode 644" sh -      
	  echo "k3S node named $HOSTNAME installed with node ip $NODE_IP."  
	EOF
	
end

config.vm.define WORKER_NAME do |worker|
	worker.vm.hostname = WORKER_NAME
	worker.vm.network :private_network, ip: WORKER_IP 
	worker.vm.provision "shell", env: {"NODE_IP" => WORKER_IP, "MASTER_IP" => MASTER_IP, "MASTER_HOSTNAME" => MASTER_NAME, "TOKEN" => K3S_TOKEN},
	inline:  <<-EOF
		set -eu
		echo "$MASTER_IP $MASTER_HOSTNAME" >> /etc/hosts
		curl -sfL https://get.k3s.io \
		  | INSTALL_K3S_EXEC="--server=https://${MASTER_HOSTNAME}:6443 --node-ip=${NODE_IP} --token=${TOKEN}" sh -
		echo "k3S node named $HOSTNAME installed with node ip $NODE_IP."
	EOF
	end
end