# -*- mode: ruby -*-
# vi: set ft=ruby :


# master config
MASTER_NAME = 'ybenbraiS'
MASTER_IP = '192.168.42.110'

#agent config
WORKER_NAME = 'ybenbraiSW'
WORKER_IP = '192.168.42.111'

# common config
MEMORY = 1024
CPU = 1
BOX = "centos/8"
# BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"
BOX_UPDATE = false

# disable firewall so we can have direct ssh access without need to copy our ssh public key to the machine 
# !!! (NOT RECOMMENDED , USE THE SSH KEYS METHOD IN PRODUCTION ENV, THIS IS ONLY FOR SCHOOL PRACTICING PURPOSE ) !!!
$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL


Vagrant.configure("2") do |config|
	config.vm.box = BOX
	# config.vm.box_url = BOX_URL
	config.vm.box_check_update = BOX_UPDATE
	# config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT 
  
	config.vm.provider "virtualbox" do |v|
		v.memory = MEMORY
		v.cpus = CPU
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.define MASTER_NAME do |master|
		master.vm.hostname = MASTER_NAME
		master.vm.network :private_network, ip: MASTER_IP
		master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		master.vm.provision "shell", privileged: true, path: "scripts/master_setup.sh", args: [MASTER_IP]

		master.vm.provider "virtualbox" do |v|
			v.name = MASTER_NAME
			# v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
		end
	end

	config.vm.define WORKER_NAME do |worker|
		worker.vm.hostname = WORKER_NAME
		worker.vm.network :private_network, ip: WORKER_IP 
		worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		worker.vm.provision "shell", privileged: true, path: "scripts/worker_setup.sh", args: [MASTER_IP, WORKER_IP]

		worker.vm.provider "virtualbox" do |v|
			v.name = WORKER_NAME
			# v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
		end
	end
end